name: retriever-rag
services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./apps/server/Dockerfile
    ports:
      - "49152:49152"
    environment:
      - NODE_ENV=production
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://host.docker.internal:11434
    depends_on:
      - qdrant
    volumes:
      - ./:/app/
    stdin_open: true
    networks:
      - app_network

  worker:
    container_name: worker
    build:
      context: ./
      dockerfile: ./apps/worker/Dockerfile
    environment:
      - NODE_ENV=production
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://host.docker.internal:11434
      - PROJECT_PATH=data
    depends_on:
      - qdrant
    volumes:
      - ./:/app/
    stdin_open: true
    networks:
      - app_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  qdrant_data:
